title: Hey! # your name (or website title) here
logo: "/images/download20200402154839.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! My name is Alyssa Marie Dico Maravilla
  <br><br>
  I'm make things.
  <br><br>  
  
  <br><br>
  Thanks for checking out my page!
  <br><br>
  <a href="https://www.linkedin.com/in/alyssam-maravilla/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://twitter.com/alohasushicore/">Icon Credit @alohasushicore on Twitter!~</a>
  <br><br>
  <a href="/resume">Current Resume</a>
  <br><br>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
